version: 0.2

env:
  parameter-store:
    PACKER_GITHUB_API_TOKEN: "/demo/ec2/gh_token"

phases:
  install:
    commands:
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.8.3/packer_1.8.3_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq..."
      - curl -qL -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && chmod +x ./jq
  pre_build:
    commands:
      - echo "Validating Packer Template"
      - ./packer init .
      - ./packer validate aws_ubuntu.pkr.hcl
  build:
    commands:
      - echo "Building Packer AMI"
      - ./packer build -machine-readable aws_ubuntu.pkr.hcl | tee build.log
      - "export AMI_IDENT=$(grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2)"
      - echo $AMI_IDENT
  post_build:
    commands:
      - echo $AMI_IDENT > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - echo "HashiCorp Packer build completed"
artifacts:
  files:
    - ami_id.txt
